---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Introduction to R
================

### Children's Mercy Hospital

-----

:calendar: February 28, 2025

:alarm_clock: 8 am - 5 pm

:computer: [Workshop Github](https://github.com/FridleyLab/CMH_Introduction_to_R)

-----

## Setup

The workshop will be hosted in person at Children's Mercy Hospital in Kansas City. 
Please come with R and RStudio already installed on your computer. 

<!-- 
* When you're done, put a green post-it on your computer. 
* If you need help, put up a pink post-it.
-->

## Slides

<!--
* Rewrite as links to slides on github once they are made
* [Name of talk](path/to/slides.pdf)
-->

* Introduction and R and Rmarkdown
* Data Manipulation I and II
* Visualization with ggplot
* Statistical testing
* Best practices

## Code

Find our live coded notes in [`notes/`](notes/) as we commit them.

## Questions?

Feel free to ask questions in the [GitHub Issues](https://github.com/FridleyLab/CMH_Introduction_to_R/issues).

## Overview

This is a 1 day workshop designed to introduce future users to R and Rstudio.
We will cover data cleaning using the `tidyverse`, creating visuals with `ggplot`,
basic statistical analysis and writing documents with `Rmarkdown`. In the end 
you should be able to: 

<!--
Each instructor should provide a one sentence summary of what participants
will be able to do after thier lecture 
-->

* import and manipulate data into different formats
* create new variables and recode existing ones 
* plot data using the appropriate figure type 
* perform basic statistics
* write Rmarkdown reports

## Who is this course designed for?

Have you never written any code in R or any other programming language? Are you
familiar with R, but hoping to bulk up your basic skills? Have you used R but are
new to the `tidyverse` framework? 

## Learning objectives

Introduction to R/Rstudio and Rmarkdown

  - Get familiar with the R and Rstudio environment
  - Understand basic R code structure (packages, data structures)
  - Create and render `Rmarkdown` documents in multiple formats 
    
Data import and manipulation - Part I

  - Import various data types 
  - Explain the fundamentals of "tidy data" and the `tidyverse`
  - Clean data sets using `dplyr` verbs
    
Data manipulation and cleaning - Part II

  - Merge data sets
  - Transform data  
    
Visualization 

  - Understand the principles of `ggplot2`
  - Determine appropriate visualizations 
  - Plot - `geom_smooth` to see a model over the data 
    
Basic statistics 

  - ttest, correlation and chisq 
  - Model data 
  - Report findings from R output 

## Materials/RStudio Cloud

Materials will be made available on [GitHub](https://github.com/FridleyLab/CMH_Introduction_to_R).  If you are using an organization-issued laptop, you may want to verify before you arrive that you can access GitHub.

## Schedule and Links

*   8:00 - 8:15 - Welcome
*   8:15 - 9 - Intro to R and Github
*   9 - 10 - data import and clean
*   10 - 10:15 - break
*   10:15 - 11:30 - data cleaning continued
*   11:30 - 12:30 - Intro to ggplot2

## Instructors

<!--
Add links to personal websites and double check personal info
* add small blurbs/pictures for each instructor? 
-->

This workshop is taught by Jordan Creed and Alex Soupir and sponsored by Brooke Fridley.

-----
